/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/url/{slug}": {
    /** Retrives the url of a given slug */
    get: operations["getUrl"];
  };
  "/latest": {
    /** Retrives the latest n created slug */
    post: operations["latest"];
  };
  "/create-link": {
    /** Creates a short link */
    post: operations["createLink"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: never;
  responses: {
    /** @description Error response */
    error: {
      content: {
        "application/json": {
          message: string;
          code: string;
          issues?: ({
              message: string;
            })[];
        };
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  /** Retrives the url of a given slug */
  getUrl: {
    parameters: {
      path: {
        slug: string;
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": {
            url: string;
          };
        };
      };
      default: components["responses"]["error"];
    };
  };
  /** Retrives the latest n created slug */
  latest: {
    requestBody: {
      content: {
        "application/json": {
          api_key: string;
          /** @default 3 */
          n?: number;
        };
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": (unknown)[];
        };
      };
      default: components["responses"]["error"];
    };
  };
  /** Creates a short link */
  createLink: {
    requestBody: {
      content: {
        "application/json": {
          api_key: string;
          url: string;
          expiresAt?: string | null;
          slug?: string | null;
        };
      };
    };
    responses: {
      /** @description Successful response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      default: components["responses"]["error"];
    };
  };
}
